CREATE TABLE IF NOT EXISTS ALI_IMAGENES (
    ID_IMAGEN SERIAL PRIMARY KEY,
    CODIGO_ALI BIGINT NOT NULL REFERENCES MUESTRAS_ALI(CODIGO_ALI) ON DELETE CASCADE,
    S3_KEY VARCHAR(255) NOT NULL,
    NOMBRE_ARCHIVO VARCHAR(255),
    TIPO_MIME VARCHAR(100),
    TAMANIO BIGINT,
    FECHA_SUBIDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);