version: '3.8'

services:

  #Base de datos
  BD_AsisTec:
    image: postgres:17 # Usar una versión estable (16). La 18 no existe oficialmente aún.
    container_name: contenedor_asistec_bd
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${MI_CLAVE_POSTGRES}
      - POSTGRES_DB=${NOMBRE_DB}
      - TZ=America/Santiago
      - PGTZ=America/Santiago
    volumes:
      - ./BD/postgres/init_refined.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data # Ruta estándar para evitar el error de "data in /var/lib/postgresql"

  backend_asistec:
    build: ./Backend
    volumes:
      - ./Backend:/app
      - /app/node_modules
      - ./.env:/app/.env
    container_name: "contenedor_asistec_backend"
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=${MI_CLAVE_POSTGRES}
      - DB_HOST=BD_AsisTec # Nombre del servicio de arriba
      - DB_NAME=${NOMBRE_DB}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - BD_AsisTec

volumes:
  pgdata:
