-- init_refined.sql
-- Script definitivo para PostgreSQL - Proyecto AsisTec
-- Modularización de RAM y Compatibilidad con Backend Asistec
-- --------------------------------------------------------
-- 1. CONFIGURACIÓN INICIAL
-- --------------------------------------------------------
-- DROP SCHEMA IF EXISTS public CASCADE;
-- CREATE SCHEMA public;
-- --------------------------------------------------------
-- 2. TABLAS MAESTRAS (Catálogos)
-- --------------------------------------------------------
CREATE TABLE DILUYENTES (
    ID_DILUYENTE SERIAL PRIMARY KEY,
    NOMBRE_DILUYENTE VARCHAR(100) NOT NULL,
    MILILITROS VARCHAR(50) NOT NULL
);
CREATE TABLE EQUIPOS_INCUBACION (
    ID_INCUBACION SERIAL PRIMARY KEY,
    NOMBRE_EQUIPO VARCHAR(100) NOT NULL,
    TEMPERATURA_REF VARCHAR(50)
);
CREATE TABLE EQUIPOS_LAB (
    ID_EQUIPO SERIAL PRIMARY KEY,
    NOMBRE_EQUIPO VARCHAR(100) NOT NULL,
    CODIGO_EQUIPO VARCHAR(50)
);
CREATE TABLE INSTRUMENTOS (
    ID_INSTRUMENTO SERIAL PRIMARY KEY,
    NOMBRE_INSTRUMENTO VARCHAR(100) NOT NULL,
    CODIGO_INSTRUMENTO VARCHAR(50)
);
CREATE TABLE LUGARES_ALMACENAMIENTO (
    ID_LUGAR SERIAL PRIMARY KEY,
    NOMBRE_LUGAR VARCHAR(100) NOT NULL,
    CODIGO_LUGAR VARCHAR(20)
);
CREATE TABLE MAESTRO_CHECKLIST_LIMPIEZA (
    ID_ITEM INT PRIMARY KEY,
    NOMBRE_ITEM VARCHAR(100) NOT NULL,
    DEF_SELECCIONADO INT DEFAULT 0,
    DEF_BLOQUEADO INT DEFAULT 0
);
CREATE TABLE MAESTRO_FORMAS_CALCULO (
    ID_FORMA INT PRIMARY KEY,
    NOMBRE_FORMA VARCHAR(100) NOT NULL,
    DEF_SELECCIONADO INT DEFAULT 0
);
CREATE TABLE MAESTRO_TIPOS_ANALISIS (
    ID_TIPO_ANALISIS SERIAL PRIMARY KEY,
    NOMBRE_ANALISIS VARCHAR(100) NOT NULL
);
CREATE TABLE MATERIAL_SIEMBRA (
    ID_MATERIAL_SIEMBRA SERIAL PRIMARY KEY,
    NOMBRE_MATERIAL VARCHAR(100) NOT NULL,
    DETALLE_MEDIDA VARCHAR(100)
);
CREATE TABLE MICROPIPETAS (
    ID_PIPETA SERIAL PRIMARY KEY,
    NOMBRE_PIPETA VARCHAR(100) NOT NULL,
    CODIGO_PIPETA VARCHAR(50) NOT NULL,
    CAPACIDAD VARCHAR(20)
);
CREATE TABLE USUARIOS (
    RUT_ANALISTA VARCHAR(20) PRIMARY KEY,
    NOMBRE_APELLIDO_ANALISTA VARCHAR(100) NOT NULL,
    CORREO_ANALISTA VARCHAR(100) UNIQUE NOT NULL,
    CONTRASENA_ANALISTA VARCHAR(100) NOT NULL,
    ROL_ANALISTA INT DEFAULT 0 -- 0: Analista, 1: Supervisor/Admin
);
-- --------------------------------------------------------
-- 3. TABLAS OPERACIONALES (Muestras y TPA)
-- --------------------------------------------------------
CREATE TABLE MUESTRAS_ALI (
    CODIGO_ALI BIGINT PRIMARY KEY,
    CODIGO_OTROS VARCHAR(50),
    OBSERVACIONES_CLIENTE TEXT,
    OBSERVACIONES_GENERALES TEXT,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE TPA_REPORTE (
    CODIGO_ALI BIGINT PRIMARY KEY REFERENCES MUESTRAS_ALI(CODIGO_ALI) ON DELETE CASCADE,
    ID_LUGAR INT REFERENCES LUGARES_ALMACENAMIENTO(ID_LUGAR),
    OBSERVACIONES_INGRESO TEXT,
    ESTADO_ACTUAL VARCHAR(20) DEFAULT 'NO_REALIZADO',
    FECHA_CIERRE TIMESTAMP,
    USUARIO_CIERRE VARCHAR(20) REFERENCES USUARIOS(RUT_ANALISTA),
    OBSERVACIONES_FINALES TEXT,
    FIRMA_DIGITAL TEXT,
    OBSERVACIONES_GENERALES_ANALISTAS TEXT,
    FECHA_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_ULTIMA_MODIFICACION VARCHAR(20) REFERENCES USUARIOS(RUT_ANALISTA)
);
CREATE TABLE TPA_ETAPA2_SESION (
    ID_SESION SERIAL PRIMARY KEY,
    CODIGO_ALI BIGINT NOT NULL REFERENCES TPA_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    RUT_ANALISTA VARCHAR(20) REFERENCES USUARIOS(RUT_ANALISTA),
    FECHA_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_TERMINO TIMESTAMP,
    NUMERO_MUESTRAS VARCHAR(50),
    OBSERVACIONES_SESION TEXT,
    RETIRO_PESADO INT DEFAULT 0,
    LUGAR_ALMACENAMIENTO VARCHAR(100)
);
CREATE TABLE TPA_ETAPA2_EQUIPOS (
    ID_USO_EQUIPO SERIAL PRIMARY KEY,
    ID_SESION INT NOT NULL REFERENCES TPA_ETAPA2_SESION(ID_SESION) ON DELETE CASCADE,
    ID_EQUIPO INT NOT NULL REFERENCES EQUIPOS_LAB(ID_EQUIPO)
);
CREATE TABLE TPA_ETAPA2_MATERIALES (
    ID_USO_MATERIAL SERIAL PRIMARY KEY,
    ID_SESION INT NOT NULL REFERENCES TPA_ETAPA2_SESION(ID_SESION) ON DELETE CASCADE,
    TIPO_MATERIAL VARCHAR(20) NOT NULL,
    ID_PIPETA INT REFERENCES MICROPIPETAS(ID_PIPETA),
    ID_INSTRUMENTO INT REFERENCES INSTRUMENTOS(ID_INSTRUMENTO),
    CODIGO_MANUAL VARCHAR(100)
);
CREATE TABLE TPA_ETAPA3_CHECKLIST (
    ID_CHECKLIST SERIAL PRIMARY KEY,
    CODIGO_ALI BIGINT NOT NULL REFERENCES TPA_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    NOMBRE_ITEM VARCHAR(100) NOT NULL,
    SELECCIONADO INT DEFAULT 0,
    BLOQUEADO INT DEFAULT 0
);
CREATE TABLE TPA_ETAPA4_RETIRO (
    ID_RETIRO SERIAL PRIMARY KEY,
    CODIGO_ALI BIGINT NOT NULL REFERENCES TPA_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    RUT_ANALISTA VARCHAR(20) REFERENCES USUARIOS(RUT_ANALISTA),
    FECHA_RETIRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACCION_REALIZADA TEXT,
    HORA_INICIO VARCHAR(10)
);
CREATE TABLE TPA_ETAPA5_SIEMBRA (
    ID_SIEMBRA SERIAL PRIMARY KEY,
    CODIGO_ALI BIGINT UNIQUE NOT NULL REFERENCES TPA_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    OBSERVACIONES_SIEMBRA TEXT,
    OTROS_EQUIPOS_TEXTO VARCHAR(500),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE TPA_ETAPA5_RECURSOS (
    ID_RECURSO_SIEMBRA SERIAL PRIMARY KEY,
    ID_SIEMBRA INT NOT NULL REFERENCES TPA_ETAPA5_SIEMBRA(ID_SIEMBRA) ON DELETE CASCADE,
    CATEGORIA_RECURSO VARCHAR(20) NOT NULL CHECK (
        CATEGORIA_RECURSO IN ('MATERIAL', 'DILUYENTE', 'EQUIPO')
    ),
    ID_MATERIAL_SIEMBRA INT REFERENCES MATERIAL_SIEMBRA(ID_MATERIAL_SIEMBRA),
    CODIGO_MATERIAL VARCHAR(100),
    ID_DILUYENTE INT REFERENCES DILUYENTES(ID_DILUYENTE),
    ID_INCUBACION INT REFERENCES EQUIPOS_INCUBACION(ID_INCUBACION),
    CODIGO_DILUYENTE VARCHAR(100),
    SELECCIONADO INT DEFAULT 1,
    ID_EQUIPO INT REFERENCES EQUIPOS_LAB(ID_EQUIPO)
);
-- --------------------------------------------------------
-- 4. REFACTORIZACIÓN RAM_REPORTE (Modular)
-- --------------------------------------------------------
-- Tabla Cabecera (Estado y Auditoría)
CREATE TABLE RAM_REPORTE (
    CODIGO_ALI BIGINT PRIMARY KEY REFERENCES MUESTRAS_ALI(CODIGO_ALI) ON DELETE CASCADE,
    ESTADO_RAM VARCHAR(20) DEFAULT 'Borrador',
    UFC_FINAL_REPORTE NUMERIC(15, 2),
    -- Importante para cálculo consolidado
    FIRMA_COORDINADOR TEXT,
    FECHA_ULTIMA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_ULTIMA_MODIFICACION VARCHAR(20) REFERENCES USUARIOS(RUT_ANALISTA)
);
-- Etapa 1: Siembra
CREATE TABLE RAM_ETAPA1_SIEMBRA (
    CODIGO_ALI BIGINT PRIMARY KEY REFERENCES RAM_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    AGAR_PLATE_COUNT VARCHAR(50),
    ID_EQUIPO_INCUBACION INT REFERENCES EQUIPOS_INCUBACION(ID_INCUBACION),
    -- Se mantiene aquí por flujo UI
    HORA_INICIO_HOMOGENIZADO VARCHAR(10),
    HORA_TERMINO_SIEMBRA VARCHAR(10),
    MICROPIPETA_UTILIZADA VARCHAR(100),
    N_MUESTRA_10GR VARCHAR(100),
    N_MUESTRA_50GR VARCHAR(100)
);
-- Etapa 2: Incubación
CREATE TABLE RAM_ETAPA2_INCUBACION (
    CODIGO_ALI BIGINT PRIMARY KEY REFERENCES RAM_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    ID_RESPONSABLE_ANALISIS VARCHAR(20) REFERENCES USUARIOS(RUT_ANALISTA),
    ID_RESPONSABLE_INCUBACION VARCHAR(20) REFERENCES USUARIOS(RUT_ANALISTA),
    FECHA_INICIO_INCUBACION DATE,
    FECHA_FIN_INCUBACION DATE,
    HORA_INICIO_INCUBACION VARCHAR(10),
    HORA_FIN_INCUBACION VARCHAR(10)
);
-- Etapa 3: Muestras (Cálculos directos)
CREATE TABLE RAM_ETAPA3_MUESTRAS (
    ID_MUESTRA SERIAL PRIMARY KEY,
    CODIGO_ALI BIGINT NOT NULL REFERENCES RAM_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    NUMERO_MUESTRA INT NOT NULL,
    DIL_1 NUMERIC(10, 5),
    DIL_2 NUMERIC(10, 5),
    C1 INT,
    C2 INT,
    C3 INT,
    C4 INT,
    RESULTADO_RAM VARCHAR(100),
    RESULTADO_RPES VARCHAR(100),
    PROMEDIO_COLONIAS VARCHAR(100),
    N1 INT,
    N2 INT,
    SUMATORIA_COLONIAS INT,
    FACTOR_DILUCION NUMERIC(15, 2)
);
-- Etapa 3: Duplicados
CREATE TABLE RAM_ETAPA3_DUPLICADO (
    CODIGO_ALI BIGINT PRIMARY KEY REFERENCES RAM_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    ID_MUESTRA_ORIGINAL INT REFERENCES RAM_ETAPA3_MUESTRAS(ID_MUESTRA) ON DELETE CASCADE,
    DIL_DUP_1 NUMERIC(10, 5),
    DIL_DUP_2 NUMERIC(10, 5),
    C_DUP_1 INT,
    C_DUP_2 INT,
    C_DUP_3 INT,
    C_DUP_4 INT,
    RESULTADO_RAM_DUP VARCHAR(100),
    RESULTADO_RPES_DUP VARCHAR(100),
    PROMEDIO_COLONIAS_DUPLICADO VARCHAR(100),
    N1_DUPLICADO INT,
    N2_DUPLICADO INT,
    SUMATORIA_COLONIAS_DUPLICADO INT,
    FACTOR_DILUCION NUMERIC(15, 2)
);
-- Etapa 4: Lectura
CREATE TABLE RAM_ETAPA4_LECTURA (
    CODIGO_ALI BIGINT PRIMARY KEY REFERENCES RAM_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    HORA_INICIO_LECTURA VARCHAR(10),
    HORA_FIN_LECTURA VARCHAR(10),
    TEMPERATURA NUMERIC(5, 2),
    BLANCO_UFC INT,
    CONTROL_UFC INT,
    CONTROL_SIEMBRA_ECOLI INT,
    CONTROL_AMBIENTAL_PESADO NUMERIC(15, 2),
    -- Recuperado de Oracle
    UFC_CONTROL_PESADO NUMERIC(15, 2)
);
-- Etapa 5: Verificación
CREATE TABLE RAM_ETAPA5_VERIFICACION (
    CODIGO_ALI BIGINT PRIMARY KEY REFERENCES RAM_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    LIMITE VARCHAR(50),
    MERCADO VARCHAR(100),
    FECHA_ENTREGA DATE,
    HORA_ENTREGA VARCHAR(10),
    TABLA_PAGINA VARCHAR(50),
    DESFAVORABLE VARCHAR(10),
    -- "SI" o "NO"
    MANUAL_INOCUIDAD TEXT -- Base64 o URL de la imagen del manual
);
-- Etapa 6: Aseguramiento
CREATE TABLE RAM_ETAPA6_ASEGURAMIENTO (
    CODIGO_ALI BIGINT PRIMARY KEY REFERENCES RAM_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    ID_ANALISIS_DUPLI INT REFERENCES MAESTRO_TIPOS_ANALISIS(ID_TIPO_ANALISIS),
    CONTROL_BLANCO_VAL VARCHAR(50),
    CONTROL_BLANCO_ESTADO VARCHAR(20),
    CONTROL_SIEMBRA_VAL VARCHAR(50),
    CONTROL_SIEMBRA_ESTADO VARCHAR(20),
    DUPLICADO_ALI_VAL VARCHAR(50),
    DUPLICADO_ESTADO VARCHAR(20)
);
-- Etapa 7: Cierre y Formas de Cálculo
CREATE TABLE RAM_ETAPA7_CIERRE (
    CODIGO_ALI BIGINT PRIMARY KEY REFERENCES RAM_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    OBSERVACIONES_FINALES TEXT,
    OBSERVACIONES_GENERALES_ANALISTA_RAM TEXT
);
CREATE TABLE RAM_ETAPA7_FORMAS_CALCULO (
    ID_REGISTRO SERIAL PRIMARY KEY,
    CODIGO_ALI BIGINT NOT NULL REFERENCES RAM_REPORTE(CODIGO_ALI) ON DELETE CASCADE,
    ID_FORMA INT NOT NULL REFERENCES MAESTRO_FORMAS_CALCULO(ID_FORMA),
    TIPO_USUARIO VARCHAR(20) NOT NULL -- 'ANALISTA' o 'COORDINADOR'
);
-- --------------------------------------------------------
-- 5. VISTAS Y UTILIDADES
-- --------------------------------------------------------
CREATE OR REPLACE VIEW V_CATALOGO_UNIFICADO AS
SELECT id_instrumento AS id_origen,
    nombre_instrumento AS nombre,
    codigo_instrumento AS codigo,
    'INSTRUMENTO' AS tipo_material,
    NULL::VARCHAR AS capacidad
FROM INSTRUMENTOS
UNION ALL
SELECT id_pipeta AS id_origen,
    nombre_pipeta || ' (' || capacidad || ')' AS nombre,
    codigo_pipeta AS codigo,
    'PIPETA' AS tipo_material,
    capacidad
FROM MICROPIPETAS
ORDER BY nombre ASC;
-- --------------------------------------------------------
-- 6. INSERCIÓN DE DATOS MAESTROS (Copiados de tu propusta)
-- --------------------------------------------------------
INSERT INTO DILUYENTES (NOMBRE_DILUYENTE, MILILITROS)
VALUES ('AP 0,1 90ml', '90 ml'),
    ('AP 0,1 99ml', '99 ml'),
    ('AP 0,1 450ml', '450 ml'),
    ('AP 0,1 225ml', '225 ml'),
    ('AP 0,1 500ml', '500 ml'),
    ('AP 0,1 tubosml', 'Tubos'),
    ('PBS 450 ml', '450 ml'),
    ('SPS 225 ml', '225 ml'),
    ('SPS Tubos', 'Tubos'),
    ('SPS sa 90ml', '90 ml'),
    ('SPS sa tubos', 'Tubos');
INSERT INTO EQUIPOS_INCUBACION (NOMBRE_EQUIPO, TEMPERATURA_REF)
VALUES ('Estufa 73-M (35+/-0,5C)', '35+/-0,5C'),
    ('Estufa 2-M(35.5+/-0,5C)', '35.5+/-0,5C');
INSERT INTO EQUIPOS_LAB (NOMBRE_EQUIPO, CODIGO_EQUIPO)
VALUES ('Balanza 74-M', '74-M'),
    ('Camara Flujo laminar 8-M', '8-M'),
    ('Balanza 6-M', '6-M'),
    ('Meson de Transpaso', 'MES-TR'),
    ('Balanza 99-M', '99-M'),
    ('Balanza 108-M', '108-M'),
    ('Baño-5m', '5-M'),
    ('Homogenizador 12-m', '12-M'),
    ('Cuenta colonias 9-M', '9-M'),
    ('Cuenta Colonias 101-m', '101-M'),
    ('pHmetro 93-m', '93-M');
INSERT INTO INSTRUMENTOS (NOMBRE_INSTRUMENTO, CODIGO_INSTRUMENTO)
VALUES ('Cuchara', 'cuchara'),
    ('Bisturí', 'bisturi'),
    ('Pinzas', 'pinzas');
INSERT INTO LUGARES_ALMACENAMIENTO (NOMBRE_LUGAR, CODIGO_LUGAR)
VALUES ('Freezer 33-M', 'FR-33M'),
    ('Refrigerador 33-M', 'RF-33M'),
    ('Mesón Siembra', 'MES-SIEM'),
    ('Gabinete sala Transpaso', 'GAB-TRANS');
INSERT INTO MAESTRO_CHECKLIST_LIMPIEZA (
        ID_ITEM,
        NOMBRE_ITEM,
        DEF_SELECCIONADO,
        DEF_BLOQUEADO
    )
VALUES (1, 'Mesón', 1, 1),
    (2, 'Stomacher 12-M', 0, 0),
    (3, 'Cámara Flujo laminar 8-M', 0, 0),
    (4, 'Balanza 74-M/108-M', 0, 0),
    (5, 'Balanza 6-M/99-M', 0, 0),
    (6, 'Gabinete', 0, 0),
    (7, 'Desinfectante en aerosol', 1, 1);
INSERT INTO MAESTRO_FORMAS_CALCULO (ID_FORMA, NOMBRE_FORMA, DEF_SELECCIONADO)
VALUES (1, 'Calculadora', 0),
    (2, 'Plantillas Excel (Almacenar)', 0),
    (3, 'Software', 1);
INSERT INTO MAESTRO_TIPOS_ANALISIS (NOMBRE_ANALISIS)
VALUES ('Ram'),
    ('Hongos'),
    ('Ram Ruso');
INSERT INTO MATERIAL_SIEMBRA (NOMBRE_MATERIAL, DETALLE_MEDIDA)
VALUES ('Puntas 1 ML', '1 ML'),
    ('Puntas 10ML', '10 ML'),
    ('Placas estériles 57cm2/150mm', '150mm'),
    ('Asas Drigalsky', 'Estándar'),
    ('Blender', 'Unidad'),
    ('Bolsas estériles', 'Unidad'),
    ('Probeta 250 ML', '250 ML'),
    ('Probeta 100 ML', '100 ML');
INSERT INTO MICROPIPETAS (NOMBRE_PIPETA, CODIGO_PIPETA, CAPACIDAD)
VALUES ('Pipeta 22-M', '22-M', '1 ML'),
    ('Pipeta 23-M', '23-M', '1 ML'),
    ('Pipeta 72-M', '72-M', '1 ML'),
    ('Pipeta 98-M', '98-M', '1 ML'),
    ('Pipeta 100-M', '100-M', '1 ML'),
    ('Pipeta 102-M', '102-M', '1 ML'),
    ('Pipeta 32-M', '32-M', '10 ML'),
    ('Pipeta 75-M', '75-M', '10 ML'),
    ('Pipeta 94-M', '94-M', '10 ML'),
    ('Pipeta 103-M', '103-M', '10 ML'),
    ('Pipeta 106-M', '106-M', '10 ML');
-- Usuario Administrador por defecto (Contraseña: admin123 hash provisional)
INSERT INTO USUARIOS (
        RUT_ANALISTA,
        NOMBRE_APELLIDO_ANALISTA,
        CORREO_ANALISTA,
        CONTRASENA_ANALISTA,
        ROL_ANALISTA
    )
VALUES (
        '1-9',
        'Administrador Asistec',
        'admin@asistec.cl',
        '$2b$10$abcdefghijklmnopqrstuvwxyz12345',
        1
    );