-- AlterTable
ALTER TABLE "coli_fase4_resultado" ADD COLUMN IF NOT EXISTS "ecoli_categoria_rareza" SMALLINT,
ADD COLUMN IF NOT EXISTS "ecoli_estado" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "ecoli_limite_inferior" DECIMAL(15,4),
ADD COLUMN IF NOT EXISTS "ecoli_limite_superior" DECIMAL(15,4),
ADD COLUMN IF NOT EXISTS "ecoli_log10_mpn" DECIMAL(15,6),
ADD COLUMN IF NOT EXISTS "ecoli_rarity_index" DECIMAL(15,6),
ADD COLUMN IF NOT EXISTS "ecoli_sd_log10" DECIMAL(15,6),
ADD COLUMN IF NOT EXISTS "fecales_categoria_rareza" SMALLINT,
ADD COLUMN IF NOT EXISTS "fecales_estado" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "fecales_limite_inferior" DECIMAL(15,4),
ADD COLUMN IF NOT EXISTS "fecales_limite_superior" DECIMAL(15,4),
ADD COLUMN IF NOT EXISTS "fecales_log10_mpn" DECIMAL(15,6),
ADD COLUMN IF NOT EXISTS "fecales_rarity_index" DECIMAL(15,6),
ADD COLUMN IF NOT EXISTS "fecales_sd_log10" DECIMAL(15,6),
ADD COLUMN IF NOT EXISTS "totales_categoria_rareza" SMALLINT,
ADD COLUMN IF NOT EXISTS "totales_estado" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "totales_limite_inferior" DECIMAL(15,4),
ADD COLUMN IF NOT EXISTS "totales_limite_superior" DECIMAL(15,4),
ADD COLUMN IF NOT EXISTS "totales_log10_mpn" DECIMAL(15,6),
ADD COLUMN IF NOT EXISTS "totales_rarity_index" DECIMAL(15,6),
ADD COLUMN IF NOT EXISTS "totales_sd_log10" DECIMAL(15,6);

